### ISSUE TITLE
Should Ergo serialized/deserialize CTO objects

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#157]
Currently the JavaScript backend works on CTO objects by exporting them to JSON on input and reimporting them from JSON on output. Should the compiler and runtime target native CTO objects directly?

**Comment by dselman** [comment]
"Native CTO objects" are the JS objects with additional functions and internal properties, so I believe Ergo should be able to work with them directly. The serialization process just drops some of the properties and only returns the data.

**Comment by jeromesimeon** [comment]
We may want to distinguish both code generation for pure JSON and for "Native CTO objects". The later might be needed for Ergo execution on Hyperledger Fabric, while the former could be used for serverless execution without dependencies to composer packages.

**Comment by jeromesimeon** [comment]
Ergo uses CTO-validated JSON objects as of 0.7.0
