### ISSUE TITLE
Support for optional chaining

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#192]
The composer modeling language (CTOs) allow for optional values. There is limited support to handle such values in Ergo at the moment. A possible direction is to allow pattern matching `match...with... else` on optional values. A complementary and convenient language construct is to enable optional chaining in the style of Swift (see https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/OptionalChaining.html)

**Comment by kach** [comment]
Match/with already works on optionals?

**Comment by kach** [comment]
It seems that `??` and `?.` also work.

**Comment by jeromesimeon** [comment]
Yes this issue was left open for further review and left behind...
