### ISSUE TITLE
Reserved keywords are not allows as property names

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/ergo#199]
For example `contract` is a reserved keyword.

However the following statement should be valid:
```
return new Payment{ contract: "xyz" } 
```

This returns a ParseError in Ergo v0.0.61

**Comment by jeromesimeon** [comment]
Fixed in #205 added an entry in the smoke test as well: https://github.com/accordproject/ergo/blob/59ccb7d3ef76a7b655b6e15899f779d0ed18eebb/examples/smoke/logic.ergo#L13
