### ISSUE TITLE
Support for tuples?

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#20]
It might be useful to have a tuple type in Ergo. The typical use case is for a function or a clause that needs to return multiple values. See the corresponding issue in https://github.com/accordproject/cicero/issues/37

**Comment by jeromesimeon** [comment]
This might be implemented on top of #21.

**Comment by kach** [comment]
The language doesn't need tuples if it already has records.

**Comment by jeromesimeon** [comment]
Speaking for @mttrbrts in absentia, his original use case had to do with writing functions returning two things.

I tend to agree that we can do without it, especially that we don't have a way to write pairs in CTO. -- We don't have a way to write records in CTO either, but it feels less of a stretch.

**Comment by jeromesimeon** [comment]
I'd like to vote for @kach 's suggestion that the language does not need tuples. For returning two values in a function, the use of records is relatively convenient (no need to declare a type for those).

```
define function pairOf(x: Integer, y:String) : { left: Integer, right: String } {
  return { left: x, right: y }
}

return pairOf(1, "thing").right
Response. "thing" : String
```

**Comment by jeromesimeon** [comment]
@mttrbrts Any objection to closing this issue with no action?

**Comment by mttrbrts** [comment]
Yes, I'm happy with record support. Thanks both.
