### ISSUE TITLE
Add emits declaration to a clause signature

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/ergo#201]
To support this requirement https://github.com/accordproject/cicero/issues/116, ergo clause signature declarations should include a single event type e.g.

```
clause myClause(request: Request): Response emits PaymentNotice {
```

**Comment by jeromesimeon** [comment]
There is now a syntax for emits, mirroring the one for `throws` as suggested. I am wondering if additional support is needed, e.g., `@AccordProject` style annotation in the generated code to indicate emit types?

**Comment by jeromesimeon** [comment]
See #205

**Comment by mttrbrts** [comment]
That would allow us to have more specific Type information in clients through a getEventTypes API for example?

**Comment by jeromesimeon** [comment]
Yes that would be the idea. In JavaScript, the logic is usually annotated as follows:
```
/**
 * Execute the smart clause
 * @param {Context} context - the Accord context
 * @param {org.accordproject.ippayment.PaymentRequest} context.request - the incoming request
 * @param {org.accordproject.ippayment.PayOut} context.response - the response
 * @AccordClauseLogic
 */
```

If using Ergo, a similar comment is created at code-generation time based on the type signature of the clause so there is less of a risk of inconsistency.

In either cases, we could mandate the presence of those annotations to know what type of events are being produced. Part of the question is whether this is the right way for applications to consume those types.

Another approach might be to generate function signatures in a JSON format that could be more easily consumed, or a kind of "class interface".

**Comment by jeromesimeon** [comment]
With 2db4c78a585189f328ac93964cc048fe6baad8c7 in, here is the new generated code with emit type annotations:
```
/**
 * Execute the smart clause
 * @param {Context} context - the Accord context
 * @param {org.accordproject.installmentsale.Installment} context.request - the incoming request
 * @param {org.accordproject.installmentsale.Balance} context.response - the response
 * @param {org.accordproject.installmentsale.PaymentObligation} context.emit - the emitted events
 * @AccordClauseLogic
 */
function InstallmentSale_PayInstallment(context) {
...
```

This should dovetail with https://github.com/accordproject/cicero/issues/116
