### ISSUE TITLE
Unary negation happens on nats, not floats (parser issue)

### ISSUE THREAD

**Issue by kach** [accordproject/ergo#247]
So you can have lots of fun with this…

```
ergotop$ -2
{nat: -2.0}
ergotop$ -2.0
0.0
ergotop$ -0.2
0.2
```

Proposal: `-` for unary negation of floats, `~` for nats. Or somehow allow `-` for both nats and floats if possible.

**Comment by jeromesimeon** [comment]
Fixed in PR #252
