### ISSUE TITLE
Add native support for DateTime operators

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#255]
Currently DateTime operators can only be evaluated when compiling to JavaScript. We should provide a native implementation for those operators either in Coq or OCaml for the extracted code. This can then be used for the reference interpreter (See #4) or the REPL (See #25).

**Comment by kach** [comment]
Wait, wait, what do you mean by "native" and what operators are there? DateTime can get very very hairy very very quickly and if this code has legal implications then I think more thought needs to be put into it.

**Comment by jeromesimeon** [comment]
The existing dateTime operators are listed in: https://github.com/accordproject/ergo/blob/3dbc6f54d1206069d6f5ae7a7f3b49ba1d50b5fd/extraction/stdlib/stdlib.ergo#L7

In the JavaScript target for the Ergo compiler those are backed up by the moment library (http://momentjs.com). In eval those are not implemented.

We definitely need some more revision/design for those, but this issue is just about `eval` not supporting any of them.

**Comment by jeromesimeon** [comment]
Could be possibly better addressed through #345 which would make it portable.

**Comment by jeromesimeon** [comment]
Addressed in PR #397
