### ISSUE TITLE
VSCode plugin for Ergo

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#26]
We need some initial support for editing, syntax highlighting, etc.

**Comment by jeromesimeon** [comment]
Plugin for hyperledger composer is a useful pointer: https://github.com/hyperledger/composer-vscode-plugin

**Comment by mttrbrts** [comment]
Released https://marketplace.visualstudio.com/items?itemName=accordproject.accordproject-vscode-plugin

Source at https://github.com/accordproject/ergo-vscode-plugin
