### ISSUE TITLE
Functions no longer work in the REPL because name resolution gets confused

### ISSUE THREAD

**Issue by kach** [accordproject/ergo#261]
```
ergotop$ define constant pi = 3.14

ergotop$ define function area(r : Integer) : Integer { return pi * r^2.0 }

ergotop$ return area(1.0) ;
Compilation error at 2:7-2:16 'Cannot find function with name 'area''
```

The problem is that we never tell name resolution that `area` got defined. It exists in the dynamic context but not in the static context. The solution would be to somehow preserve both static and dynamic context when evaluating each line of the repl. But I'm not sure how to actually implement that, because I don't quite understand the name resolution hooks. @jeromesimeon?

Also, do we even want two kinds of context or can we merge them? Maybe the right answer is to have a single context, parameterized as "static" or "dynamic" by giving it the type of each name bound in the environments — either `ergo_type` for static or `ergo_data` for dynamic… that might simplify typechecking as well because a lot of the code for context handling could be factored out as common.

**Comment by jeromesimeon** [comment]
That makes sense. And yes I think we want to consolidate the context so it is shared for both compilation and eval.

**Comment by jeromesimeon** [comment]
Can we close this?

**Comment by kach** [comment]
Yeah.
