### ISSUE TITLE
Document REPL

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#276]
The current note on `ergotop` in the main README is confusing since it assumes the user has followed developers instructuctions. We should provide a more detailed installation instruction. We should also add a section on the REPL in the online documentation.

**Comment by kach** [comment]
See #298

**Comment by kach** [comment]
Better instructions can be added once we do an Ergo release that makes `ergotop` available via npm.

**Comment by jeromesimeon** [comment]
Instructions in https://docs.accordproject.org/docs/accordproject.html would be most useful

**Comment by jeromesimeon** [comment]
Documented here: https://docs.accordproject.org/docs/ergo-cli.html#ergotop-repl
