### ISSUE TITLE
Generalize ergo expression map

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#278]
The ergo inlining module supports a generic notion of `map` over expressions which would be useful in other parts of the systems (e.g., to handle parts of the compilation code, for optimization). We should consider generalizing and moving that code to a common module.

**Comment by kach** [comment]
What do you mean by "generalizing"; can you be more specific? What are your use-cases?

**Comment by kach** [comment]
Well ergo_map_expr needs to know what type ctxt is so that it can add names to ctxt as it descends into e.g. a `let` binding's body.

**Comment by jeromesimeon** [comment]
Looking at the code, I'm now really confused. The only place where the ctxt is being changed is in Let:https://github.com/accordproject/ergo/blob/3dbc6f54d1206069d6f5ae7a7f3b49ba1d50b5fd/mechanization/Ergo/Lang/ErgoInline.v#L80
But the corresponding part of the environment is only accessed in:
https://github.com/accordproject/ergo/blob/3dbc6f54d1206069d6f5ae7a7f3b49ba1d50b5fd/mechanization/Ergo/Lang/ErgoEval.v#L82
which does not seem to rely on the generic inlining?

Maybe I'm missing something... It would be useful to clean up and document this part of the code. Hopefully #275 will help.

Also, you could try and generalize with an additional function (fctxt: C -> ergo_expr -> option C)

**Comment by kach** [comment]
#289
