### ISSUE TITLE
Add match desugaring to compiler (ergo -> ergo calculus)

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#281]
Match are not desugared in the translation from ergo to ergo calculus. It could be handled in a way similar to `foreach` to simplify subsequent compilation steps or to simplify the evaluation at the calculus level.

**Comment by jeromesimeon** [comment]
I don't think this is done?

**Comment by kach** [comment]
Yeah but it doesn't need to be done — everything works as it is. The foreach desugaring was required to implement foreach in the typechecker and the typechecker. The match desugaring is not required.
