### ISSUE TITLE
Remove "inlining" for foreach in eval

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#283]
Foreach is now desugared at the ergo calculus level. The similar inlining on foreach should be removed from the evaluation code over ergo calculus.

**Comment by kach** [comment]
Yes, will do today.

**Comment by jeromesimeon** [comment]
Addressed in #285. The code for individual "foreach inline" is still there, but not used. It may be useful to keep for when we refactor actual function inlining (and possible revision of Ergo to ErgoCalculus).

**Comment by jeromesimeon** [comment]
Reopening, as some of the eval should be changed to work only on Ergo calculus expressions (no `This` and multi-foreach with where clauses).
