### ISSUE TITLE
Make sure we can run on OCaml 4.07 and Coq 8.8.1

### ISSUE THREAD

**Issue by kach** [accordproject/ergo#299]
Currently, things are set up to work with OCaml 4.06.1 and Coq 8.8.0…

**Comment by jeromesimeon** [comment]
Everything works fine without changes using Coq 8.8.1.

I used:
```
opam update
opam upgrade
```

(still with OCaml 4.06.1)

**Comment by jeromesimeon** [comment]
Updated developers instructions and the CircleCI script in #308
