### ISSUE TITLE
Warnings in compiler

### ISSUE THREAD

**Issue by kach** [accordproject/ergo#300]
We need infrastructure to emit compiler warnings, e.g. for version mismatch (#245).

Seems like the `eresult` type could be modified such that a `Success` includes both the result _and_ a list of warnings. Then by modifying `elift` appropriately, it shouldn't be hard to integrate this change into the codebase.

**Comment by jeromesimeon** [comment]
Infrastructure for warnings added in #625 and cleaned up in #630
