### ISSUE TITLE
Disallow multiple definitions of the same name

### ISSUE THREAD

**Issue by kach** [accordproject/ergo#303]
This kind of thing should _not_ be allowed in the compiler (but ideally _should_ be allowed in the REPL for the sake of experimentation). The check can be implemented as part of the typechecker.

```
define constant x = 5
define constant x = 6
```

**Comment by jeromesimeon** [comment]
I don't see a problem with this code. Also having the REPL behavior differ from the one in Ergo is a nuisance since we have to maintain both behaviors.

**Comment by jeromesimeon** [comment]
Enums support is based on constants, which means there can be shadowing. We should make this a compiler warning (using the recently added #300 support).
