### ISSUE TITLE
New inlining code is not complete

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#309]
The new inlining code for the ErgoC intermediate representation cannot be used by the compiler in its current form due to missing support for several feature, notably contracts, and match expressions (see also #282).

**Comment by kach** [comment]
It seems you took care of contracts this morning. Do you want me to do `match`?

**Comment by kach** [comment]
see PR #318

**Comment by jeromesimeon** [comment]
The only TODO left relates to support for the standard library. See #295 
Closing this issue.
