### ISSUE TITLE
string_of_error_plus in compiler

### ISSUE THREAD

**Issue by kach** [accordproject/ergo#324]
> @jeromesimeon could you convert the compiler's code to use string_of_error_plus? You just need to give it the full source as the second argument so that it knows the string to underline. After that, we can delete the old string_of_error and rename string_of_error_plus to string_of_error. I'll then add better formatting (eg colorization iff stdout is a tty).

(From #322)

**Comment by kach** [comment]
(I'd also like to output errors to stderr rather than stdout.)

**Comment by kach** [comment]
Where do I get the raw text for the compiler? Not sure how it's structured.

**Comment by jeromesimeon** [comment]
hm.. assuming I understood your question: depends at which place you are looking at.

- In `extraction/src/ErgoCompile.ml` the function `ergo_proc` has the `file_content` string.
- In `extraction/ergoc.ml` the function `main` has `input_files` which are file names loaded using `ErgoUtil.process_file`

**Comment by jeromesimeon** [comment]
Some improvements: ```bash-3.2$ ./bin/ergoc.native examples/bad-logic/logic.ergo 
[ParseError at file examples/bad-logic/logic.ergo line 17 col 20] 
contract HelloWorld ovr TemplateModel {
                    ^^^                
bash-3.2$ ergoc examples/bad-logic/logic.ergo 
18:59:01 - info: Logging initialized. 2018-08-04T22:59:01.091Z
18:59:01 - error: [ParseError at file examples/bad-logic/logic.ergo line 17 col 20] 
contract HelloWorld ovr TemplateModel {
                    ^^^                
bash-3.2$ ./bin/ergotop examples/bad-logic/logic.ergo 
[ParseError at file examples/bad-logic/logic.ergo line 17 col 20] 
contract HelloWorld ovr TemplateModel {
                    ^^^                
```

**Comment by jeromesimeon** [comment]
In PR #369
