### ISSUE TITLE
new or not new, that is the question

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#326]
It has been suggested ( more than once ) that we could do without the `new` syntax when creating objects (concepts/assets/contracts/transactions/events). So instead of:

```
new Request{ input : "gift card" }
```

One would write:
```
Request{ input : "gift card" }
```

or with a fully qualified name (using the recently adopted syntax with `~`):
```
~org.accordproject.HelloWorld{ input : "gift card" }
```

Note: this is one of the syntaxes allowed in golang, so not entirely without precedent https://www.golang-book.com/books/intro/9

This might also make the contract setting declaration in the REPL a little nicer (See #277):
```
set contract SupplyAgreement over TemplateModel{ buyer : "Dan", seller : "Matt" }
```

**Comment by jeromesimeon** [comment]
Note that this is relatively easy to do, but we lose the ability to write `new constant{ .. }`. I.e., the following will not work:
```
namespace foo.bar
define constant{ x: String }
constant{ x: "hi" }
```

since `constant` is a keyword in the language.

One will have to write instead:
```
namespace foo.bar
define constant{ x: String }
~foo.bar.constant{ x : String }
```

This is probably a problem we can live with

**Comment by kach** [comment]
I'm confused about your examples in the comment above… but other than that seems fine?

**Comment by jeromesimeon** [comment]
@kach updated the examples with a correct syntax (:frowning:). Does that help?
