### ISSUE TITLE
Write type inference for Ergo expressions

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#328]
We need inference at the level of ergo expressions, without function calls. This should be a function with the following signature:

```
TypeModel -> TypeContext -> Expr -> Type
```

Where
- `TypeModel` contains the type declared in CTO files and type definitions (including the type hierarchy)
- `TypeContext` contains type assignments for all the free variable in the expression
- `Expr` is the expression being type checked
- `TypeOut` is the type of the output

**Comment by kach** [comment]
Expr is an "ergo calculus" expression not an ergo expression?

Also how do the typing rules work when there's this "type hierarchy"?

**Comment by jeromesimeon** [comment]
I would start with ErgoC expressions, yes which should be a lot easier as a starting point and that's where eval is as well, so we would have the chance to place typing and eval side by side for soundness.

You will want to use built-in operators on branded values using`brand` `unbrand` and `cast` which have sound type cheking rules in their underlying formalization. e.g., This steps into Qcert territory, you can find the type checking rules for operators here:

https://querycert.github.io/html/Qcert.Common.OperatorsTyping.TUnaryOperators.html#unary_op_type

https://querycert.github.io/html/Qcert.Common.OperatorsTyping.TBinaryOperators.html#binary_op_type

**Comment by kach** [comment]
Does type inference happen pre-inline or post-inline?

**Comment by jeromesimeon** [comment]
Good question. Any suggestion?

**Comment by kach** [comment]
Pre-inline means we need to explicitly handle typing rules for function calls, which means maintaining information about function types in the context. But then the type errors make more sense to the user.

**Comment by kach** [comment]
Are we using the type defns in Common/Types/ErgoTypes.v?

**Comment by jeromesimeon** [comment]
The inference will be much easier on `Backend/Lib/ECType.v` i.e., after building a type model (with record types for concepts, etc expanded).

The basic idea is to go from:

```
define concept Animal{ name : String, group: String }
define concept Cow extends Animal{ color : String }
define concept Cat extends Animal{ breed: String }
```
or
```
concept Animal{ o String name o String group }
concept Cow extends Animal{ o String color }
concept Cat extends Animal{ o String breed }
```
to
```
Brand Animal = {name : String, group : String, .. }  // { .. } for open record
Brand Cow = {name : String, group : String, color : String, .. }
Brand Cat = {name : String, group : String, breed : String, .. }
Cow extends Animal
Cat extends Animal
```

which becomes a model over which we can check things like proper subtyping relation, compute least upper bound and greatest lower bound, etc

That step corresponds to #329

**Comment by jeromesimeon** [comment]
Typing rules for function calls are interesting. The underlying type system does support lambdas with the standard contra variant rule.

**Comment by kach** [comment]
wheeeeee #347

**Comment by kach** [comment]
(It's a start.)

**Comment by kach** [comment]
(Done in #356)
