### ISSUE TITLE
Type inference for functions, clauses, contracts, declarations

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#331]
We need support for type inference over declarations:
- [x] Functions with parameters `p1`, .. `pn`, and output type `p0` this should rely almost directly on type inference for expressions (#328)
- [x] Clauses, similarly as for functions
- [x] Contracts, which are groups of clauses (or functions)
- [x] Constant declarations, based on type inference for expressions
- [x] Calls to clauses in contracts, based on type inference for expressions

**Comment by kach** [comment]
(Functions done ✅ )

**Comment by jeromesimeon** [comment]
Now contracts / Set contract / Call contract work as well, remains to turn all this on in the compiler
