### ISSUE TITLE
Document reserved words

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#34]
The list of reserved words (language used by the language such as `contract`, `function`, etc that can't be identifiers) should be documented.

**Comment by mttrbrts** [comment]
- [ ] contract
- [ ] clause
- [ ] function
- [ ] variable
- [ ] define
- [ ] emit
- [ ] set state

**Comment by jeromesimeon** [comment]
There is now a completely list based on the lexer in the new documentation: https://ergo.accordproject.org/docs/ergo-ref-lexical.html#reserved-words
