### ISSUE TITLE
Document precedence of operators and expressions

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#35]
We should have a documentation for the precedence of expressions/operators in the language. See the one from Java for example: https://docs.oracle.com/javase/tutorial/java/nutsandbolts/operators.html

**Comment by luckymurari** [comment]
Is there a way to know the precedence of expressions/operators either from the code or somewhere else?

**Comment by jeromesimeon** [comment]
@luckymurari At the moment from the code itself (or through testing). The parser is at https://github.com/accordproject/ergo/blob/master/extraction/src/ErgoParser.mly

I quite like the kind of table you find for Java: https://introcs.cs.princeton.edu/java/11precedence/

Are you interested in taking that on @luckymurari ?

**Comment by Ashiroq** [comment]
Hi, I want to work on this one.
I assume pull request for this issue should be in [techdocs](https://github.com/accordproject/techdocs), correct?
Is chapter on [operators](https://github.com/accordproject/techdocs/blob/master/docs/logic-simple-expr.md#operators) the best place for the table?

**Comment by jeromesimeon** [comment]
> Hi, I want to work on this one.
> I assume pull request for this issue should be in [techdocs](https://github.com/accordproject/techdocs), correct?
> Is chapter on [operators](https://github.com/accordproject/techdocs/blob/master/docs/logic-simple-expr.md#operators) the best place for the table?

Hi @Ashiroq, great I'll assign the issue to you.

I would suggest to put it in the reference part of techdocs. Probably as a new Section here: https://docs.accordproject.org/docs/ref-logic.html (https://github.com/accordproject/techdocs/blob/master/docs/ref-logic.md)

**Comment by Ashiroq** [comment]
Made pull request at https://github.com/accordproject/techdocs/pull/235

**Comment by jeromesimeon** [comment]
@Ashiroq Great! This will have to be maintained, and can use some examples but this is a great start. Closing this issue.
