### ISSUE TITLE
Zero division has lots of behaviors

### ISSUE THREAD

**Issue by kach** [accordproject/ergo#388]
```
ergo$ return 1.0 / 0.0;
Response. inf
  :  {emit: Unit[], response: Double, state: Unit}?
ergo$ return 0.0 / 0.0;
Response. nan
  :  {emit: Unit[], response: Double, state: Unit}?
ergo$ return 1 /i 0;
Response. 0
  :  {emit: Unit[], response: Integer, state: Unit}?
ergo$ return 0 /i 0;
Response. 0
  :  {emit: Unit[], response: Integer, state: Unit}?
ergo$ return sqrt(-1.0);
Response. nan
```

I'm not sure I agree with all of these outcomes (I think they should all be errors — because what happens if you try to serialize nan/inf to JSON?). But I imagine they're not up for negotiation because they're built-in to Qcert. At the very least, then, the behavior should be documented, and there should be ways to check `is_nan` or `is_infinity` from Ergo. Also, `nan` and `inf` should be globally available constants.

**Comment by jeromesimeon** [comment]
I think Double behavior should be consistent with IEEE spec. I believe it is.

I think Integer behavior should be consistent with .. something. I'm less clear about that. What we see here is Coq's specification for Z (I believe). There is some possibly useful text here:
https://stackoverflow.com/questions/29282819/coq-qarith-division-by-zero-is-zero-why

Also: functions / expressions in Ergo have to be total.

**Comment by kach** [comment]
I mean, sure, it's not hard to make things consistent with a spec. But Ergo's users don't know/care about the spec, because they're focused on other things. They will write things like this:

```java
clause yearly_performance_review(request : Request) {
  let output_per_hour = request.total_lines_of_code_written / request.time_worked;
  if output_per_hour < 10.0 { // not working hard enough
    emit LayoffObligation {};
    return "done";
  } else {
    emit RaiseObligation {};
    return "done";
  }
}
```
and now a person who has 0.0 output and worked 0.0 hours will be given a raise.

I'm sure we can find a way to make arithmetic exceptions cause errors (like enforce) or emit warnings or _something_. If the goal is to protect users, then saying "it matches a spec" isn't helpful.

**Comment by jeromesimeon** [comment]
I won't comment on how easy/hard it is to make a IEEE 754 implementation -- I just hope no-one else sees this :)

Just couple of points: when we generate code, we have to generate operations on a target language. IEEE floating points are one of the few datatypes well supported across pretty much  all languages. Defining yet another kind of floating point number semantics is actually hard, and generating code for that semantic will be even harder.

Your example is really good, but I would do that with a library (maybe internally based on floats, or maybe based on an arbitrary precision datatype to avoid issues of rounding). Enforce/warning checks could then happen inside that library. If the library is written in Ergo then we avoid problems of portability.

**Comment by jeromesimeon** [comment]
A few more things about this issue, before I close it 🙂 

1. I'm adding a "question" label to the issue
2. `sqrt(-1.0)` is a good illustration of why `NaN` is in the IEEE spec for floating points
3. JSON's inability to properly support JavaScript `numbers` is quite a flaw, but sadly well documented. Various not very convincing workarounds are documented here: https://stackoverflow.com/questions/1423081/json-left-out-infinity-and-nan-json-status-in-ecmascript
4. This is indeed leading to problem when exporting Ergo values to JSON. See #643 and some suggested resolutions.
5. Ergo's semantic for `Double` is well founded, based on the flocq formalisation of IEEE 754 (https://www.lri.fr/~melquion/doc/11-arith20-article.pdf) -- but compilation targets underlying implementations for IEEE 754 (number in JavaScript, float in OCaml, etc) so we will have to keep an eye on that.
