### ISSUE TITLE
Perform inline expansion on Ergo as a separate phase

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#42]
Inline expansion is the main source of compiler error (e.g., calling a function that isn't in scope or hasn't been declared). It would make the compiler code simpler and easier to debug if it was performed as a first step before translation to calculus.

**Comment by jeromesimeon** [comment]
Reviewing some of the compilation pipeline as part of the work in #25 and #223 it seems the new ErgoCalculus would be the right place to implement inlining.

**Comment by kach** [comment]
I think inlining should be its own AST pass. That's how it's implemented in the REPL right now — it goes through once and inlines globals in functions, then it goes through again and inlines functions in expressions. We can more or less move that code verbatim higher upstream if you'd like.

**Comment by jeromesimeon** [comment]
replaced by #275
