### ISSUE TITLE
arraySubstract - Typo in Stdlib

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/ergo#450]
https://github.com/accordproject/ergo/blob/878d83090f23a7eb763a3be01fc7cedd7a54ce62/mechanization/ErgoC/Lang/ErgoCStdlib.v#L167

It appears that the fully qualified name of the arraySubtract method in the StdLib contains a typo.

Compiling `arraySubtract(xs, ys)` yields: 
```
12:12:11 - info:  kind=SystemError, message=Built in function org.accordproject.ergo.stdlib.arraySubtract not found, line=24, character=18, line=24, character=60, verbose=System error. Built in function org.accordproject.ergo.stdlib.arraySubtract not found
```

Compiling `arraySubstract(xs, ys)` yields: 
```
12:12:25 - info:  kind=CompilationError, message=Cannot find function with name 'arraySubstract', line=24, character=18, line=24, character=61, verbose=Compilation error (at file lib/logic.ergo line 24 col 18). Cannot find function with name 'arraySubstract' 
```

I'm happy to open a PR, is this any where else that this reference needs to be changed?

**Comment by jeromesimeon** [comment]
In https://github.com/accordproject/ergo/releases/tag/v0.4.1
