### ISSUE TITLE
Math & Geo Libraries

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/ergo#472]
I need to calculate the distance between two locations in the logic of a contract.

In order to do that I need to use the haversine formulae (https://en.wikipedia.org/wiki/Haversine_formula). There are some notes on implementation here:
https://www.movable-type.co.uk/scripts/latlong.html

This will require the following primitive Math constants & functions in Ergo:
- Pi
- Sine
- Cosine
- Arctan

This also motivates the need for reuseable Math and Geo libraries for Ergo logic.

**Comment by jeromesimeon** [comment]
Handled by PR #556 ?
