### ISSUE TITLE
Switch to dune build tool

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#481]
https://dune.build

This seems to be the future (and already present) of build tools for OCaml.

**Comment by pranabs1ngh** [comment]
Hey, can you please assign this issue to me?

**Comment by jeromesimeon** [comment]
> Hey, can you please assign this issue to me?

Sounds great @pranabs1ngh I'm not super familiar with dune, but I should still be able to help. My idea was to use it to replace `ocamlbuild` in the OCaml part of the code in the `./extraction` directory. Let me know if that makes sense.

**Comment by jeromesimeon** [comment]
@pranabs1ngh Do you need any help with this?

**Comment by pranabs1ngh** [comment]
Hey, sorry for not responding. I was busy with my exams. Will work on it ASAP.

I will ask for help when needed!!

**Comment by pranabs1ngh** [comment]
I think I won't be able to work on this for now. Sorry, for such irresponsible behavior, but I can't give time on this.

Kindly, move this issue to open issues for now.

**Comment by jeromesimeon** [comment]
no worries @pranabs1ngh !

**Comment by jeromesimeon** [comment]
This is done and merged into the `release-1.0` branch.
