### ISSUE TITLE
Typo in ergo-runtime.js causes dateTimeSubtract() to fail

### ISSUE THREAD

**Issue by benariss** [accordproject/ergo#482]
Using the standard library function dateTimeSubtract causes the execution to fail with the error

> TypeError: date.substract is not a function
>      at dateTimePointMinus (vm.js:1013:17)

This looks to be being caused by a typo in the dateTimePointMinus function in ergo-runtime.js where you are calling date.sub**s**tract rather than date.subtract

**Comment by jeromesimeon** [comment]
Thanks! Looking into it.

**Comment by jeromesimeon** [comment]
Fixed in PR #486
