### ISSUE TITLE
Add support for Time Periods alongside Durations

### ISSUE THREAD

**Issue by benariss** [accordproject/ergo#483]
Alongside the existing support for fixed durations of time, there should also be support for relative time periods such as months and quarters for DateTime manipulation in Ergo and related data types in the template models.
These would be used in cases where a time period is specified in the clause, for example where a contract is valid for X months from its inception date.  To correctly calculate the end date of the contract we would require the functionality to modify the date with the number of months rather than converting this to a number of weeks or days in a Duration either programatically or forcing the clause text to be in a less natural form (i.e. valid for 109 days).

**Comment by jeromesimeon** [comment]
Time Period were added in 0.6, support for end/start of period taking timezones into account was added in 0.7.
