### ISSUE TITLE
CLI version is incorrect

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/ergo#487]
After installing the ergo cli, the version numbers reported by the tools are wrong.

```
npm i -g @accordproject/ergo-cli@0.5.7
```
```
mattmbp:bin matt$ ergoc --version
The Ergo compiler, version 0.5.6
```

However when building from source, the version is reported correctly. Perhaps the tools weren't rebuilt before committing?
```
mattmbp:bin matt$ ./ergoc.native --version
The Ergo compiler, version 0.5.7
```

**Comment by jeromesimeon** [comment]
The deployment script automatically changes `Version.v` which is used to get the version native number, but this requires a full rebuild when it occurs. We should review/revise the build process to handle this better.

**Comment by jeromesimeon** [comment]
Note this is a duplicate issue, see #305

**Comment by mttrbrts** [comment]
Closing as duplicate of #305. Thanks @jeromesimeon
