### ISSUE TITLE
Arrays indexers

### ISSUE THREAD

**Issue by HamidMoutawakkil** [accordproject/ergo#561]
So far I wasn't able to find indexers function in arrays, and I cannot extract one item from an array. 
Even with the foreach with the condition, an array is returned. 

It would be interesting to have the usual:
```
let lst = [1,2,3]
let item = getItem(lst, 1); // to retrieve the item under the index 1
let item = lst[1]; // more natural
let last = getLast(lst); // returns the last
let first = getFirst(lst); // returns the first
```

if predicates are supported something like:
`let goodItem = find(itemList, x.id == "someId");
`

**Comment by jeromesimeon** [comment]
I will add `getSingleton` to this list... maybe that's a good name  for its to align with the other accessors.

**Comment by jphillips-bp3** [comment]
Yup, I am hitting this problem now also. I like the predicate idea a lot.

> let goodItem = find(itemList, x.id == "someId");

**Comment by dselman** [comment]
The Singleton function was added here: https://github.com/accordproject/ergo/releases/tag/v0.6.3

**Comment by jeromesimeon** [comment]
Support for array index access is ready in the markdown branch https://github.com/accordproject/ergo/tree/js-experiment-markdown

Proposed syntax:
```
e1[e2]
```
where `e1` and `e2` are expressions, with `e1` of type array and `e2` of type `Long`.

The result of that function is an option.

Examples:
```
Welcome to ERGOTOP version 0.8.2
ergo$ return ["foo","bar"][0]
Response. some("foo") : String?
ergo$ return [1,2][2]
Response. none : Integer?
ergo$ return { a : [1,2,3] }.a[1]
Response. some(2) : Integer?
ergo$ return [1,2][-1]
Response. none : Integer?
ergo$ 
```

**Comment by jeromesimeon** [comment]
The work is completed in #623 with syntax and semantics as shown in the previous message.

Please re-open if any concern/questions.
