### ISSUE TITLE
Double rounding function for N decimal places required

### ISSUE THREAD

**Issue by jphillips-bp3** [accordproject/ergo#570]
I have hit a need in the demo I am building for a client to be able to round up/down to the nearest decimal place. Currently there is a `floor` and `ceil` function for `Double`s that rounds to the nearest integer but nothing more "precise" that I can see.

I need to get confirmation to the exact rounding strategy they want, for example like those found in Java `BigDecimals` so will update here: https://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html

**Comment by jeromesimeon** [comment]
BigNumber support is not available at the moment, so we are limited by what you can do with JavaScript numbers (IEEE floats really).

For rounding based on precision, we've used things like this:
```
define function round(x:Double) {
    return floor(x + 0.5)
}
define function roundn(x:Double, n:Integer) {
    let nd = integerToDouble(n);
    let e = 10.0 ^ nd;
    return round(x * e) / e
}
```

Example:
```
return roundn(131.41517,2)
Response. 131.42 : Double
return roundn(131.41517,3)
Response. 131.415 : Double
return roundn(131.41517,4)
Response. 131.4152 : Double
```

**Comment by jphillips-bp3** [comment]
OK thanks, I will use your examples above.

**Comment by jphillips-bp3** [comment]
That works, thanks so closing.
