### ISSUE TITLE
Unable to find the arraySubtract function

### ISSUE THREAD

**Issue by jphillips-bp3** [accordproject/ergo#573]
The compiler (e.g. Visual Studio) claims it cannot find the function `arraySubstract`. I am using `arrayAdd` so it is able to see what is under the `ord.accordproject.ergo.stdlib` package space.

**Comment by jphillips-bp3** [comment]
I have updated my `ergoc` to the latest version (0.6.3) and `cicero` (0.10.2) but still no luck.

**Comment by jeromesimeon** [comment]
how about `arraySubtract` ?

**Comment by jphillips-bp3** [comment]
Lol that will teach me to copy and paste from the documentation!

https://docs.accordproject.org/docs/ergo-stdlib.html#functions-on-arrays

**Comment by jeromesimeon** [comment]
ouch. that is indeed not helpful! I'll fix it in the documentation.
(yvw)
