### ISSUE TITLE
Can the toString() function format numbers according to their type?

### ISSUE THREAD

**Issue by jphillips-bp3** [accordproject/ergo#575]
I am using the `toString` function to turn a `Long` type into a `String`. For example when I call `toString(myDate.getYear())` it returns `2019.0` instead of just `2019`. I have tried this on an `Integer` and get a decimal place tacked onto the end of it as well.

Would it be possible for `toString` to be type aware and format numerical types appropriately?

**Comment by jeromesimeon** [comment]
That's a good request, and even could be considered a bug.

**Comment by jeromesimeon** [comment]
A fix for this is being worked on in the "Dynamic Templates" branch https://github.com/accordproject/ergo/tree/js-feature-dynamic-templates

This fix relies on the ability to distinguish between Integer and Double in the JavaScript runtime.

**Comment by jeromesimeon** [comment]
Fixed in the `0.20` branch. Test here in the REPL:

<img width="682" alt="Screenshot 2019-10-14 at 3 19 25 PM" src="https://user-images.githubusercontent.com/670099/66777154-3567a200-ee96-11e9-812c-7581a01af8f5.png">
