### ISSUE TITLE
"arraySubtract" function behaviour correct after flipping params

### ISSUE THREAD

**Issue by jphillips-bp3** [accordproject/ergo#576]
I have seen some odd behaviour twice now in my code and I think I have found a problem but would need someone to check the implementation of the function to be sure.

The `arraySubtract` function has the following documented signature:
![image](https://user-images.githubusercontent.com/4510278/54531931-72aa9680-497e-11e9-9d0f-21cc7de0b87d.png)

But, it is behaving as if X and Y are flipped, e.g. "Removes elements of x in y".

**Comment by jeromesimeon** [comment]
Looks right to me in the REPL:

<img width="420" alt="Screen Shot 2019-03-19 at 8 58 22 AM" src="https://user-images.githubusercontent.com/670099/54607627-2fefc980-4a25-11e9-937f-f6ae3861cde1.png">

**Comment by jphillips-bp3** [comment]
OK thanks for looking, will go back and re-check my code.

**Comment by jeromesimeon** [comment]
I was able to reproduce the issue with the JavaScript backend, which returns `[4]` instead of `[1]`.
It's definitely a bug.

**Comment by jphillips-bp3** [comment]
Oh OK. So does ERGOTOP use a different engine, or is it the JS that is generated is being transformed incorrectly?

**Comment by jeromesimeon** [comment]
ERGOTOP uses an interpreter (which is meant to be used as a reference semantics). Cicero uses the compiler to JavaScript. So yes, this is a bug in the JavaScript compiler.

There is no transformation once the JavaScript code has been produced (unless you consider the NodeJS compiler as one such transformation but it's unlikely to be a bug there).

**Comment by jphillips-bp3** [comment]
OK thanks for the explanation, good to know how these things work.

When do you expect to get a fix done? I ask because I am due to hand over the code to the client at the end of next week, and I will need to synchronise a new release of Cicero with a change to the code.

**Comment by jeromesimeon** [comment]
There is an upcoming major release which I thought this would go into. I could do a minor release just for this, but I'd rather not add that to my plate right now.

**Comment by jphillips-bp3** [comment]
OK thats fine, do you have an ETA for the major release? If that is after we hand over the code then I will need to document this and tell the client they will have to make a code change.

**Comment by jphillips-bp3** [comment]
As discussed, we will stay on 0.6.3/10.3 for the client to maintain stability and document why the params are flipped.

**Comment by jeromesimeon** [comment]
PR here: https://github.com/accordproject/ergo/pull/580

**Comment by jeromesimeon** [comment]
Done in 0.7.0
