### ISSUE TITLE
AP Documentation Sync

### ISSUE THREAD

**Issue by irmerk** [accordproject/ergo#620]
## Tasks
- Implement updated Accord Project documentation.

**Comment by jeromesimeon** [comment]
Can you explain what this issue is about?

**Comment by irmerk** [comment]
Sure thing. I am synchronizing the documentation to all the major repos in AP to follow what was initially changed in Cicero UI. That is, an AP footer in the README and updated contribution guidelines.

**Comment by jeromesimeon** [comment]
Ah, I get it now, thanks! The word "documentation" confused me.

**Comment by irmerk** [comment]
Closed with #621, may want to reopen with updates to `DEVELOPERS.md`
