### ISSUE TITLE
Remove unneeded encapsulation of Concerto / Concerto Tools

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#634]
Ergo/Cicero use an uncommon idiom of packaging a dependency (`composer-concerto` and `composer-concerto-tools`) to avoid problems with multiple versions of the concerto package.

The corresponding code is at: https://github.com/accordproject/ergo/blob/66feaf68fda20fed3cc8d01ba9e5c08c1b565984/packages/ergo-compiler/index.js#L22

This can be removed whenever the corresponding issues has been resolved: https://github.com/hyperledger/composer-concerto/issues/47 and

**Comment by jeromesimeon** [comment]
This work can proceed now that `@accordproject/concerto` is out

**Comment by gahag** [comment]
Sorry for asking this, but is removing those requires the only thing to be done? I'm trying to understand so I can work on it.

**Comment by jeromesimeon** [comment]
Once it is removed, every place using the exported `module.exports.ComposerConcerto` will break, so should be replaced by a proper import of the `composer-concerto` package itself. I'm afraid this particular issue cannot be fixed on `master` which still uses an older version of concerto.

I'm afraid this particular issue can only be fixed on `master` which still uses an older version of Concerto. So I've re-labelled it for the `0.20-alpha` release and removed the `Hacktoberfest` tag.

**Comment by jeromesimeon** [comment]
PRs on this are still welcome, obviously! 😃

**Comment by jeromesimeon** [comment]
Fixed in `0.20` branch
