### ISSUE TITLE
Release Notes (v0.20)

### ISSUE THREAD

**Issue by irmerk** [accordproject/ergo#646]
## Tasks
- This will track and construct the overall release notes for this repo in relation to the `v0.20` project

### Release Notes:
[Ergo v0.20 Wiki](https://github.com/accordproject/ergo/wiki/v-0.20.0)
### Documentation:
[Techdocs Ergo](https://github.com/accordproject/techdocs/issues/86)

## Related Issues:
- [Cicero Issue 412](https://github.com/accordproject/cicero/issues/412)

**Comment by jeromesimeon** [comment]
Some initial release notes can be found here: https://github.com/accordproject/ergo/wiki/v-0.20.0

**Comment by irmerk** [comment]
# Working Release Notes:

# :butterfly:

### This `v0.20` release is focused on overhauling the following Accord Project technologies:

- Dynamic Templates
  - Template Syntax
- Markdown Support
  - Markdown Syntax 
  - Markdown Transformations

It also includes newly supported enums for Ergo, as well as bug fixes.

**Note**: _This release requires changes to application and template code ..._

### 🚀 New Features

- Ability to embed Ergo expressions within your templates
- A more consistent and generalizable syntax

#### Language

- [#392][cicero392]: New string template syntax `` `This is text with {{% expression %}} and more text` `` (@jeromesimeon)
- #3: Support for enumerated values, with proper typing and pattern matching support (@jeromesimeon)
- #143: Expression sublanguage for modifying state (@jeromesimeon)
- #<Issue/PR>: Markdown support (headings, lists, emphasis, etc) (@jeromesimeon)
- #<Issue/PR>: List parsing and generation support (@jeromesimeon)

#### Standard Library

- #<Issue/PR>: New `encode` and `decode` functions (@jeromesimeon)
- #<Issue/PR>: New `format` function for `DateTime` (@jeromesimeon)
- #<Issue/PR>: New `getOptions` function which returns global static options for the compiler (e.g., `wrapVariables`) (@jeromesimeon)

### 🐛 Bug Fixes

- #642: `now` is no longer a magic variable (@jeromesimeon)
- #575: `toString` now properly format numeric values based on their types (@jeromesimeon)
- #465: Constants are now properly imported and scoped, and can be accessed using an explicit namespace (@jeromesimeon)
- #644: Cicero target properly includes type hierarchy (@jeromesimeon)
- #645: Type soundness of match expression (@jeromesimeon)

[cicero392]: https://github.com/accordproject/cicero/issues/392

**Comment by irmerk** [comment]
# Ergo v0.20 :butterfly:

### This release is focused on overhauling the following Accord Project technologies:

- Dynamic Templates
  - Template Syntax
- Markdown Support
  - Markdown Syntax 
  - Markdown Transformations

It also includes newly supported enums for Ergo and setting a specific field in the state of your contract, as well as bug fixes.

**Note**: _This release requires changes to application and template code ..._

### 🚀 New Features

- [#392][cicero392]: String template syntax `` `This is text with {{% expression %}} and more text` `` (@jeromesimeon)
- #3: Support for enumerated values, with proper typing and pattern matching support (@jeromesimeon)
- #143: Expression sublanguage for modifying state (@jeromesimeon)
- Ability to embed Ergo expressions within your templates
- A more consistent and generalizable syntax

#### 📜 Language

- Markdown support (headings, lists, emphasis, etc)
- List parsing and generation support

### 🛰 New Command Line

A and improved command line for Ergo which better aligns with the rest of the Accord Project [Cicero #425][cicero425]
```
ergo <command>

Commands:
  ergo draft       create a contract text from data
  ergo trigger     send a request to the contract
  ergo invoke      invoke a clause of the contract
  ergo initialize  initialize the state for a contract
  ergo compile     compile a contract

Options:
  --help         Show help                                             [boolean]
  --version      Show version number                                   [boolean]
  --verbose, -v                                                 [default: false]
```

#### 📚 Standard Library

- New `encode` and `decode` functions for URI encoding
- New `format` function for `DateTime`
- New `getOptions` function which returns global static options for the compiler

### ⚙️ Compiler

- #303: Redefining a constant is now a compiler warning (@jeromesimeon)

### 🏗 Build

- #688: Ergo and CI now run on Node.js v10 (@jeromesimeon)
- #623: Upgrade to [Q*cert 1.4.1][qcert] (@jeromesimeon)
- #690: Improved Windows support (@jeromesimeon)

### 🐛 Bug Fixes

- #642: `now` is no longer a magic variable (@jeromesimeon)
- #575: `toString` now properly format numeric values based on their types (@jeromesimeon)
- #465: Constants are now properly imported and scoped, and can be accessed using an explicit namespace (@jeromesimeon)
- #644: Cicero target properly includes type hierarchy (@jeromesimeon)
- #645: Type soundness of match expression (@jeromesimeon)
- #665: String with escaped characters are properly printed in REPL without an extra `\`

[cicero392]: https://github.com/accordproject/cicero/issues/392
[cicero425]: https://github.com/accordproject/cicero/issues/425
[qcert]: https://github.com/querycert/qcert/releases/tag/v1.4.1
