### ISSUE TITLE
Error Messaging Not Specific 

### ISSUE THREAD

**Issue by ZackLev** [accordproject/ergo#647]
A helpful error message here would be "missing semicolon before return", but the error displayed is just a general parsing error.  (This applies to many parsing errors).

<img width="807" alt="Screen Shot 2019-09-27 at 9 37 55 AM" src="https://user-images.githubusercontent.com/19520747/65773651-affc9780-e10a-11e9-9033-cbf3da8c936b.png">

<img width="847" alt="Screen Shot 2019-09-27 at 9 37 11 AM" src="https://user-images.githubusercontent.com/19520747/65773489-6ad86580-e10a-11e9-98a0-d57be7d720eb.png">

**Comment by jeromesimeon** [comment]
Thanks for the report. Getting better parsing errors can involve looking at all possible parsing derivations, and can be difficult to make uniform.

I would welcome suggestions and PRs on this.

**Comment by jeromesimeon** [comment]
Concrete variants of the example, all of which are parsing errors:

```
if isPaymentDay then emit return response...
if isPaymentDay then emit obligation

```

**Comment by jeromesimeon** [comment]
@ZackLev If you had examples of what you would consider "good" parsing errors from other languages, that would be very helpful!
