### ISSUE TITLE
Broken link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by arshadkazmi42** [accordproject/ergo#673]
Code of Conduct URL is broken in [CONTRIBUTING.md](https://github.com/accordproject/ergo/edit/master/CONTRIBUTING.md)

It is redirecting to https://github.com/accordproject/docs/blob/master/Accord%20Project%20Code%20of%20Conduct.pdf

I am not sure what it the correct URL for this.

If someone can give me the correct url, I can send a PR for this

**Comment by jeromesimeon** [comment]
I _believe_ it should be https://www.linuxfoundation.org/code-of-conduct/
But I would wait for a confirmation from @irmerk

**Comment by tadhglewis** [comment]
@arshadkazmi42 @jeromesimeon Updated here https://github.com/accordproject/ergo/pull/674, let me know if this link needs to changing to something else

**Comment by arshadkazmi42** [comment]
> @arshadkazmi42 @jeromesimeon Updated here #674, let me know if this link needs to changing to something else

@tadhglewis The url is not confirmed yet if its correct, we are waiting for confirmation from @irmerk 
Also, I was planning to work on this 😮

**Comment by arshadkazmi42** [comment]
@irmerk Thank you for confirming this
