### ISSUE TITLE
Revision to the Base AP model

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/ergo#698]
The Accord Project Stack relies on a base model which is included in a few places:
- In Concerto: https://github.com/accordproject/concerto/blob/master/packages/concerto-core/lib/modelloader.js
- In Ergo: https://github.com/accordproject/ergo/blob/master/extraction/stdlib/accordproject.cto (for the type checker) and here: https://github.com/accordproject/ergo/blob/master/packages/ergo-compiler/lib/builtin.js (for the validator)

This should be cleaned up and consolidated, and the difference in definition between the type checker and the validator should be addressed.

This should probably be done in conjunction with the resolution around the notion of "systems model" in Concerto. See issue https://github.com/accordproject/concerto/issues/62

**Comment by jeromesimeon** [comment]
As of Ergo `0.22.0-alpha.*` there is no more a special purpose / alternate base model for Ergo. It uses the base models as published.

**Comment by dselman** [comment]
> As of Ergo `0.22.0-alpha.*` there is no more a special purpose / alternate base model for Ergo. It uses the base models as published.

Great!
