### ISSUE TITLE
REPL does not return any response

### ISSUE THREAD

**Issue by sofiter** [accordproject/ergo#787]
**Describe the bug**
I am following the simple expressions guide. I try to copy the examples and paste them in REPL and then hit "evaluate". None of them returns any response, just a blank line is returned

**To Reproduce**
1. Go to 'https://docs.accordproject.org/docs/logic-simple-expr.html'
2. Click on 'Conditional expressions' copy button it says 
`    if 1.0 < 0.0     // Condition
    then "negative"  // Expression if condition is true
    else "positive"  // Expression if condition is false`
3. Click on ' Ergo REPL' 'link https://ergorepl.netlify.com/'
4. paste the code and hit  'Evaluate'
5. See error, nothing is returned on the right side as response/result

**Expected behavior**
Return negative or positive

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome
 - Version 87.0.4280.88

**Comment by jeromesimeon** [comment]
It shows the expected error:

<img width="750" alt="Screenshot 2020-12-09 at 11 41 41 AM" src="https://user-images.githubusercontent.com/670099/101658955-8aa83080-3a13-11eb-979f-0e970bfea819.png">

As explained here:

<img width="764" alt="Screenshot 2020-12-09 at 11 42 22 AM" src="https://user-images.githubusercontent.com/670099/101659095-ac091c80-3a13-11eb-9069-25feb22640ff.png">

 you have to prefix the expression with `return`:

<img width="742" alt="Screenshot 2020-12-09 at 11 43 28 AM" src="https://user-images.githubusercontent.com/670099/101659208-cd6a0880-3a13-11eb-81a8-b0eb4d6b139d.png">

**Comment by sofiter** [comment]
I figured out that you can paste the command on the right half of the screen and hit evaluate and it works that way. 
Maybe it is not clear because there are no instrauctions or headings where you should paste the code. 
I still don't understand what the left half of the screen does. Maybe i should close this issue as long as it works with the right screen correctly?
I am sorry for any inconvenience

**Comment by jeromesimeon** [comment]
The left can be used to e.g., setup imports, global variables, a whole contract -- it's really the context for evaluation on the right.

**Comment by sofiter** [comment]
Yes @jeromesimeon  you are right, it doesn't write it in all commands though. Additionaly it was not clear that I should paste it on the right half. Sorry about not figuring out earlier

**Comment by sofiter** [comment]
I am closing the issue since it is not an issue. Just a final note that maybe a few labels on REPL could help newbies :-)
