### ISSUE TITLE
Migrate CI/CD to GitHub Actions

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/ergo#793]
As described in  accordproject/technical-steering-committee#4
   
   Please follow the conventions in https://github.com/accordproject/concerto/pull/236
   
   - [x] Remove secrets from Travis (for AP maintainers: in Travis Repository Settings)
   - [x] Disable Travis in the configuration (for AP maintainers: Travis Personal Profile > Settings > Accord Project
   - [x] Remove `.travis.yml` and `.travis` directories in repo
   - [x] Add `.github/workflows` directory based on those in `./concerto/.github/workflows`
   - [x] Remove scripts in `./scripts` replace by those found in `./concerto/scripts`
   - [x] Fix `package.json` notable adjustments: remove some of the old scripts, make sure code coverage works
   - [x] Test build on PR with timestamps
   - [x] Test build on GitHub release with version number
   - [x] Update GitHub "branch protection" rules to point to the new workflows instead of Travis

**Comment by harsh1206** [comment]
@mttrbrts can i take work on this issue ?
