### ISSUE TITLE
durationAs calculation error minutes to hours

### ISSUE THREAD

**Issue by discochance** [accordproject/ergo#848]
Currently the durationAs implementation converts minutes into hours by multiplication of 60, which is wrong, it should be division by 60

https://github.com/accordproject/ergo/blob/650da370aa86143a5718ed70007b329b1f1d2fc9/compiler/stdlib/etime.ergo#L89

**Comment by sanjeevbhusal** [comment]
Hey, can i work on this project?

**Comment by jeromesimeon** [comment]
@discochance nice catch, thanks for the report. Fix in #865
